### ISSUE TITLE
求一份 nginx 反代的配置

### ISSUE THREAD

**Issue by 2096779623** [lxmusics/lx-music-api-server-python#9]
```conf
server {
        server_name example.com;
        listen 443 ssl;
        ssl on;
        ssl_certificate lx.crt;
        ssl_certificate_key lx.key;
        ssl_session_timeout 5m;
        ssl_protocols TLSv1.1 TLSv1.2 TLSv1.3;
        ssl_ciphers ECDHE-ECDSA-CHACHA20-POLY1305:ECDHE-RSA-CHACHA20-POLY1305:ECDHE-ECDSA-AES128-GCM-SHA256:ECDHE-RSA-AES128-GCM-SHA256:ECDHE-ECDSA-AES256-GCM-SHA384:ECDHE-RSA-AES256-GCM-SHA384:DHE-RSA-AES128-GCM-SHA256:DHE-RSA-AES256-GCM-SHA384:ECDHE-ECDSA-AES128-SHA256:ECDHE-RSA-AES128-SHA256:ECDHE-ECDSA-AES128-SHA:ECDHE-RSA-AES256-SHA384:ECDHE-RSA-AES128-SHA:ECDHE-ECDSA-AES256-SHA384:ECDHE-ECDSA-AES256-SHA:ECDHE-RSA-AES256-SHA:DHE-RSA-AES128-SHA256:DHE-RSA-AES128-SHA:DHE-RSA-AES256-SHA256:DHE-RSA-AES256-SHA:ECDHE-ECDSA-DES-CBC3-SHA:ECDHE-RSA-DES-CBC3-SHA:EDH-RSA-DES-CBC3-SHA:AES128-GCM-SHA256:AES256-GCM-SHA384:AES128-SHA256:AES256-SHA256:AES128-SHA:AES256-SHA:DES-CBC3-SHA:!DSS;
        ssl_prefer_server_ciphers on; 
    location / {
        proxy_pass http://127.0.0.1:9763;
    }
}
```

```bash
root@localhost:~/lx-music-api-server-python# python3 main.py 
2023-12-17 05:56:56|[config_manager/INFO]|HTTP协议代理地址: http://1.1.1.1:1000
2023-12-17 05:56:56|[config_manager/WARNING]|配置文件common.proxy.https_value不存在
2023-12-17 05:56:56|[config_manager/WARNING]|配置文件common.proxy.https_value不存在
2023-12-17 05:56:56|[config_manager/INFO]|代理功能已开启，请确保代理地址正确，否则无法连接网络
2023-12-17 05:56:56|[main/INFO]|监听 -> http://0.0.0.0:9763
2023-12-17 05:56:56|[main/INFO]|服务器启动成功，请按下Ctrl + C停止
2023-12-17 05:56:56|[http_utils/INFO]|-----start----- https://mips.kugou.com/check/iscn?&format=json
2023-12-17 05:56:57|[http_utils/INFO]|您在非中国大陆服务器(中国澳门)上启动了项目，已自动开启ip伪装
2023-12-17 05:56:57|[http_utils/WARNING]|此方式无法解决咪咕音乐的链接获取问题，您可以配置代理，服务器地址可在下方链接中找到
https://hidemy.io/cn/proxy-list/?country=CN#list
2023-12-17 05:57:00|[print/INFO]|Traceback (most recent call last):

2023-12-17 05:57:00|[print/INFO]|  File "/usr/local/lib/python3.9/dist-packages/aiohttp/web_protocol.py", line 452, in _handle_request
    resp = await request_handler(request)

2023-12-17 05:57:00|[print/INFO]|  File "/usr/local/lib/python3.9/dist-packages/aiohttp/web_app.py", line 543, in _handle
    resp = await handler(request)

2023-12-17 05:57:00|[print/INFO]|  File "/usr/local/lib/python3.9/dist-packages/aiohttp/web_middlewares.py", line 114, in impl
    return await handler(request)

2023-12-17 05:57:00|[print/INFO]|  File "/root/lx-music-api-server-python/main.py", line 40, in handle_request
    request.remote = request.headers.get("X-Real-IP")

2023-12-17 05:57:00|[print/INFO]|  File "aiohttp/_helpers.pyx", line 35, in aiohttp._helpers.reify.__set__

2023-12-17 05:57:00|[print/INFO]|AttributeError: reified property is read-only

Error handling request
```

没有反代的情况下是正常工作的：
```bash
D:\桌面\a\lx-music-api-server-python>python main.py
2023-12-17 14:00:45|[config_manager/DEBUG]|配置文件加载成功
2023-12-17 14:00:45|[config_manager/DEBUG]|数据库初始化成功
2023-12-17 14:00:45|[config_manager/INFO]|HTTP协议代理地址: http://1.1.1.1:1001
2023-12-17 14:00:45|[config_manager/WARNING]|配置文件common.proxy.https_value不存在
2023-12-17 14:00:45|[config_manager/WARNING]|配置文件common.proxy.https_value不存在
2023-12-17 14:00:45|[config_manager/INFO]|代理功能已开启，请确保代理地址正确，否则无法连接网络
2023-12-17 14:00:45|[http_utils/DEBUG]|HTTP Request: https://mips.kugou.com/check/iscn?&format=json
options: {'headers': {'User-Agent': 'Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/113.0.0.0 Safari/537.36'}}
2023-12-17 14:00:45|[main/INFO]|监听 -> http://0.0.0.0:9763
2023-12-17 14:00:46|[main/INFO]|服务器启动成功，请按下Ctrl + C停止
2023-12-17 14:00:46|[http_utils/INFO]|-----start----- https://mips.kugou.com/check/iscn?&format=json
2023-12-17 14:00:46|[http_utils/DEBUG]|Request to https://mips.kugou.com/check/iscn?&format=json succeed with code 200
2023-12-17 14:00:46|[http_utils/DEBUG]|{'amap_flag': -1, 'ip_flag': 1, 'amap_address': '', 'country': '中国澳门', 'flag': 1, 'errcode': 0, 'status': 1, 'error': ''}
2023-12-17 14:01:21|[config_manager/WARNING]|黑名单功能已被关闭，我们墙裂建议你开启这个功能以防止恶意请求
2023-12-17 14:01:22|[http_utils/DEBUG]|HTTP Request: https://u.y.qq.com/cgi-bin/musics.fcg?format=json&sign=
options: {'body': '{"comm":{"ct":"19","cv":"1859","uin":"0"},"req":{"module":"music.pf_song_detail_svr","method":"get_song_detail_yqq","param":{"song_type":0,"song_mid":"001DeSPX4H1umu"}}}', 'headers': {'User-Agent': 'Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/114.0.0.0 Safari/537.36 Edg/114.0.1788.0'}}
2023-12-17 14:01:22|[http_utils/INFO]|-----start----- https://u.y.qq.com/cgi-bin/musics.fcg?format=json&sign=
2023-12-17 14:01:22|[http_utils/DEBUG]|Request to https://u.y.qq.com/cgi-bin/musics.fcg?format=json&sign= succeed with code 200
2023-12-17 14:01:22|[http_utils/DEBUG]|{'code': 0, 'ts': 1702792885433, 'start_ts': 1702792885397, 'traceid': '3b9e458551258560', 'req': {'code': 0, 'data': {'info': {'company': {'title': '唱片公司', 'type': 'JUMP_TO_COMPANY', 'content': [{'id': 0, 'value': '那是家大厂牌', 'mid': '', 'type': 0, 'show_type': 0, 'is_parent': 0, 'picurl': '', 'read_cnt': 0, 'author': '', 'jumpurl': '', 'ori_picurl': ''}], 'pos': 51, 'more': 0, 'selected': 'company', 'use_platform': 1}, 'genre': {'title': '歌曲流派', 'type': 'JUMP_TO_CATEGORY', 'content': [{'id': 40, ...
2023-12-17 14:01:22|[http_utils/DEBUG]|缓存已更新: https://u.y.qq.com/cgi-bin/musics.fcg?format=json&sign=zzb75f9410b2okas6x9msrunelwdt8usw4e4cc7f2
```
![image](https://github.com/lxmusics/lx-music-api-server-python/assets/57583560/4ba77b8b-5f6a-4a9f-9021-3dcb7e7fb2f9)

**Comment by helloplhm-qwq** [comment]
等下，我的问题，马上修

**Comment by 2096779623** [comment]
还有一个问题：
```bash
D:\桌面\a\lx-music-api-server-python>python main-flask.py
2023-12-17 14:11:09|[config_manager/DEBUG]|配置文件加载成功
2023-12-17 14:11:09|[config_manager/DEBUG]|数据库初始化成功
2023-12-17 14:11:09|[config_manager/INFO]|HTTP协议代理地址: http://60.210.40.190:9091
2023-12-17 14:11:09|[config_manager/WARNING]|配置文件common.proxy.https_value不存在
2023-12-17 14:11:09|[config_manager/WARNING]|配置文件common.proxy.https_value不存在
2023-12-17 14:11:09|[config_manager/INFO]|代理功能已开启，请确保代理地址正确，否则无法连接网络
Traceback (most recent call last):
  File "D:\桌面\a\lx-music-api-server-python\main-flask.py", line 30, in <module>
    from modules import handleApiRequest
ImportError: cannot import name 'handleApiRequest' from 'modules' (D:\桌面\a\lx-music-api-server-python\modules\__init__.py)
```

**Comment by 2096779623** [comment]
```bash
root@localhost:~/lx-music-api-server-python# python3 main.py 
2023-12-17 06:16:32|[config_manager/INFO]|HTTP协议代理地址: http://1.1..1.1:1001
2023-12-17 06:16:32|[config_manager/WARNING]|配置文件common.proxy.https_value不存在
2023-12-17 06:16:32|[config_manager/WARNING]|配置文件common.proxy.https_value不存在
2023-12-17 06:16:32|[config_manager/INFO]|代理功能已开启，请确保代理地址正确，否则无法连接网络
2023-12-17 06:16:32|[main/INFO]|监听 -> http://0.0.0.0:9763
2023-12-17 06:16:32|[main/INFO]|服务器启动成功，请按下Ctrl + C停止
2023-12-17 06:16:32|[http_utils/INFO]|-----start----- https://mips.kugou.com/check/iscn?&format=json
2023-12-17 06:16:33|[http_utils/INFO]|您在非中国大陆服务器(中国澳门)上启动了项目，已自动开启ip伪装
2023-12-17 06:16:33|[http_utils/WARNING]|此方式无法解决咪咕音乐的链接获取问题，您可以配置代理，服务器地址可在下方链接中找到
https://hidemy.io/cn/proxy-list/?country=CN#list
2023-12-17 06:17:05|[config_manager/WARNING]|黑名单功能已被关闭，我们墙裂建议你开启这个功能以防止恶意请求
2023-12-17 06:17:05|[http_utils/INFO]|-----start----- https://u.y.qq.com/cgi-bin/musics.fcg?format=json&sign=zzbba3cb44dgqhxoacr2ggkrlu8doux0w98c254e2
2023-12-17 06:17:05|[http_utils/INFO]|-----start----- https://u.y.qq.com/cgi-bin/musics.fcg?format=json&sign=zzb030b25f8oelnpqpiwvm7k6zqcpia314cd1e7
2023-12-17 06:17:05|[aiohttp_web/INFO]|172.71.211.37 - GET "/url/tx/0039MnYb0qxYhV/128k", 200
```
好了，感谢大佬

**Comment by 2096779623** [comment]
```
root@C20220607177808:~/lx-music-api-server-python# python3 main-flask.py 
2023-12-17 06:20:03|[config_manager/INFO]|HTTP协议代理地址: http://1.1.1.1:1001
2023-12-17 06:20:03|[config_manager/WARNING]|配置文件common.proxy.https_value不存在
2023-12-17 06:20:03|[config_manager/WARNING]|配置文件common.proxy.https_value不存在
2023-12-17 06:20:03|[config_manager/INFO]|代理功能已开启，请确保代理地址正确，否则无法连接网络
 * Serving Flask app 'LXMusicTestAPI'
2023-12-17 06:20:03|[http_utils/INFO]|-----start----- https://mips.kugou.com/check/iscn?&format=json
 * Debug mode: off
2023-12-17 06:20:03|[flask/WARNING]|WARNING: This is a development server. Do not use it in a production deployment. Use a production WSGI server instead.
2023-12-17 06:20:03|[flask/INFO]| * Running on all addresses (0.0.0.0)
2023-12-17 06:20:03|[flask/INFO]| * Running on http://127.0.0.1:9763
2023-12-17 06:20:03|[flask/INFO]|Press CTRL+C to quit
2023-12-17 06:20:03|[http_utils/INFO]|您在非中国大陆服务器(中国澳门)上启动了项目，已自动开启ip伪装
2023-12-17 06:20:03|[http_utils/WARNING]|此方式无法解决咪咕音乐的链接获取问题，您可以配置代理，服务器地址可在下方链接中找到
https://hidemy.io/cn/proxy-list/?country=CN#list
2023-12-17 06:20:07|[config_manager/WARNING]|黑名单功能已被关闭，我们墙裂建议你开启这个功能以防止恶意请求
2023-12-17 06:20:07|[http_utils/INFO]|-----start----- https://u.y.qq.com/cgi-bin/musics.fcg?format=json&sign=zzb327e9a2ceyrkjqm5gylb10cqk31zqbf9076dc
2023-12-17 06:20:07|[http_utils/INFO]|-----start----- https://u.y.qq.com/cgi-bin/musics.fcg?format=json&sign=zzbeca65ee20xmvuylgyrjkbbamxif5jab3455712
2023-12-17 06:20:07|[flask/INFO]|127.0.0.1 - - [17/Dec/2023 06:20:07] "GET /url/tx/002usg9o4GTAKf/128k HTTP/1.0" 200 -
```
